name: resume_master
description: "A Flutter application for creating professional resumes."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  app_settings: ^6.1.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/job.jpg
    - assets/images/logo.png
    - assets/images/doodle.jpg
    - assets/images/score.jpg


