name: resume_master
description: "A Flutter application for creating professional resumes."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and core
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # Permissions and media
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/g.png
    - assets/images/onboard.jpg
    - assets/images/favicon.png
