name: resume_master
description: "A Flutter application for creating professional resumes."

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and core
  intl: ^0.20.2

  # Permissions and media

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  app_settings: ^6.1.1
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/onboard.jpg
    - assets/images/logo.png
    - assets/images/doodle.jpg
